### ISSUE TITLE
Verify if the password is correct or not

### ISSUE THREAD

**Issue by JonRC** [udbhav1/office-crypto#1]
The exposed functions return `Some` even if the password is not correct. Is there some way to use this crate to test if a password is correct or not? Do you recommend any other crate for doing that?

**Comment by udbhav1** [comment]
you can use a docx reader crate like [docx](https://crates.io/crates/docx), which will throw an error if the decrypted content is not a valid document:

```
let decrypted = decrypt_from_file(path, pw).unwrap();
let docx = DocxFile::from_reader(Cursor::new(decrypted)).expect("Incorrect password");
```

this outputs:

```
thread 'main' panicked at 'Incorrect password: Zip(InvalidArchive("Could not find central directory end"))', src/main.rs:69:66
```

in general the errors produced by `office-crypto` are file structure errors. if the file structure is valid then since this crate does not itself implement a docx reader, it has no idea if the decrypted content is garbage or correct.
